### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Getmoneyjeff** [MachineKillin/Combo-Scraper#2]
Every time I run the script. I keep getting this error. I have even added the utility.py script & pip install utility. 

localhost:~/combo# python3 gen.py
Traceback (most recent call last):
  File "/root/combo/gen.py", line 3, in <module>
    from console import utils
ModuleNotFoundError: No module named 'console'

**Comment by MachineKillin** [comment]
`pip install console`
